### ISSUE TITLE
Lists with '/' in the title cause FileNotFoundError

### ISSUE THREAD

**Issue by lukashuebner** [wasmitnetzen/wunder2ics#1]
If trying to convert a list which has a '/' in its title, the following error is thrown:
```
$ ./main.py --flatten-subtasks --subtasks-as-description --inherit-completed Tasks.json
Traceback (most recent call last):
  File "./main.py", line 124, in <module>
    sys.exit(main(args.file, args.flatten_subtasks, args.subtasks_as_description, args.inherit_completed))
  File "./main.py", line 111, in main
    write_ics(todo_list["title"], parsed)
  File "./main.py", line 102, in write_ics
    with open(f"output/{name}.ics", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/List with / in Title.ics'
```

Inspecting the folder structure of the exported archive, I guess Wunderlist is replacing '/' with '_' there.

**Comment by thiesschneider** [comment]
Hey @lukashuebner,
just had the same issue. This came also up when you have a space inside the list name. 
A workaround is to create the .ics file before running the command `touch output/LISTNAME.ics`
For the / I would rename the wunderlist list before exporting...
